Repository Coders-Evoke-Community/Amazing-Frontend_Templates, pull requests merged in 2022-10, with the labels that each got.

#137 added side-bar menu
  Templates/Side-bar/README.md
  Templates/Side-bar/index.html
  Templates/Side-bar/script.js
  Templates/Side-bar/style.css
Labels: hactoberfest-accepted

#136 added new footer design
  food_website/RESOURCES/CSS/style.css
  food_website/index.html
Labels: hacktoberfest

#184 Make a Simple Calulator using Html CSS JS
  Templates/Simple_Calculator_VimalAnand/app.js
  Templates/Simple_Calculator_VimalAnand/index.html
  Templates/Simple_Calculator_VimalAnand/styles.css
Labels: requested, hactoberfest-accepted

#181 Student BioData Card With CSS
  Templates/Student_biodata_card/1.jpg
  Templates/Student_biodata_card/index.html
  Templates/Student_biodata_card/style.css
Labels: requested, hactoberfest-accepted

#177 Medium clone frontend Responsive
  medium-Clone/1.jpg
  medium-Clone/2.jpg
  medium-Clone/3.jpg
  medium-Clone/4.jpg
  medium-Clone/5.jpg
  medium-Clone/6.jpg
  medium-Clone/index.html
  medium-Clone/style.css
Labels: hactoberfest-accepted
